### ISSUE TITLE
Remove Deprecated Processors/Classes for v2.0 

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#210]
Remove:
- [ ] EUTelProcessorApplyAlignment
- [x] EUTelProcessorHotPixelFinder
- [x] EUTelReferenceHit
- [ ] EUTelAlignmentConstant
- [ ] EUTelMatrixDecoder
- [ ] EUTelPreAlignment

This is the follow up issue from #5, aiming at the release after v1.0

**Comment by jha92** [comment]
Still open to this topic are:

- [ ] EUTelProcessorApplyAlignment
- [ ] EUTelAlignmentConstant
- [ ] EUTelMatrixDecoder

The EUTelPreAlignment will be used further.

Maybe adding more for removal at some point.

**Comment by edorossi** [comment]
The starting point of this issue is a bit old and now probably there are more processors which are obsolete. I close the issue with the idea in mind of opening a similar one starting from newer EUTelescope versions.
