### ISSUE TITLE
GBL/noDUTExample example cannot recognise patterns

### ISSUE THREAD

**Issue by kwraight** [eutelescope/eutelescope#281]
The patternRecognition steering template uses the TrackSearch processor of type EUTelProcessorPatternRecognition. However the source code for EUTelProcessorPatternRecognition is not in the current repository.

**Comment by kwraight** [comment]
Looks like implGBL folder missing from $EUTELESCOPE/src

**Comment by tbisanz** [comment]
There will be a general GBL rework in the next couple of months - thus I'm closing this for now. If you want to join the discussion - there will be a meeting on Monday 10.10.16 10:00 AM CERN time.
