### ISSUE TITLE
Z position of hits within sensor

### ISSUE THREAD

**Issue by simonspa** [eutelescope/eutelescope#315]
Currently there is no explicit convention on where to place the reconstructed hit in the local `z` coordinate of the sensitive material. Implicitly it is placed at the sensor surface by some EUTel processors, a fact that can be tested by aligning tilted telescope planes (i.e. the Timepix3 telescopes).

We should change this and do
- adhere to common standards, i.e. placing the hit in the center of the sensor, which is also more sensible from the physics point of view
- further discuss with experts in radiation damage simulation, time resolved sensors and small-depletion-depth sensors (e.g. HVCMOS) in order to develop a flexible scheme allowing the placement of the hit at configurable distances inside the sensor.

The second point does not block us from implementing the first as it would be a mere extension of the currently planned GEAR interface.

**Comment by j1990grossmann** [comment]
Furthermore it is quite difficult to account for more elaborate material stacks with the current GEAR version.
It would be desirable to be able to use GEAR also for a proper material budget estimate for the GBL fits. A module may consist of different layers of dead scatter material with different radiation length. Unfortunately for the current implementation gear::SiPlanesLayerLayout is not flexible enough to cope with that.
