### ISSUE TITLE
Add new libraries in MARLIN_DLL

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#318]
See discussion in #316

**Comment by simonspa** [comment]
To be more precise on this:
the file `ilcinstall/ilcsoft/eutelescope.py` has to be adapted to automatically add the new libraries to the generated `build_env.sh` files.

**Comment by tbisanz** [comment]
This is resolved in our new development installer - `https://svnsrv.desy.de/public/ilctools/ilcinstall/branches/v01-17-10-eutel-dev` which should be used to derive new tags. However, I'm still testing it works before closing this issue

**Comment by tbisanz** [comment]
Tested and seems to work!

**Comment by chenzhl2018** [comment]
I can't open https://svnsrv.desy.de/public/ilctools/ilcinstall/branches/v01-17-10-eutel-dev.How should I do?

**Comment by simonspa** [comment]
Two steps:

a) Use `ilcinstall` from its new home https://github.com/iLCSoft/iLCInstall
b) Drop EUTelescope and move to Corryvrekckan https://gitlab.cern.ch/corryvreckan/corryvreckan/

:slightly_smiling_face:

**Comment by jha92** [comment]
I fully second Simon with urging you to switch to Corry. Otherwise, are you using the "newer" install version of [https://github.com/eutelescope/iLCInstall](https://github.com/eutelescope/iLCInstall)?
