### ISSUE TITLE
Dockerfile installation instruction set not working for Fedora 25

### ISSUE THREAD

**Issue by TomDaub** [eutelescope/eutelescope#338]
Trying to install the development version of EUTelescope following the instructions listed in the Dockerfile.

When executing "install-ilcsoft" the xrootd module fails to build due to fixed warnings being treated as errors. Issue has been logged with the xrootd developers: https://github.com/xrootd/xrootd/issues/454

Suggested fixes are: 
1) Change compiler flags to not treat fixed warnings as errors.
2) Upgrade xrootd to latest tag (see link to xrootd issue tracker, above).

Currently trying to implement the fixes, no success yet.

**Comment by tbisanz** [comment]
We now have working versions for Fedora26, Ubuntu17, ArchLinux, SLC 6 and CernCentOS 7 - reopen if still encountering issues! XROOT will not be build by default now
