### ISSUE TITLE
Processor not registered

### ISSUE THREAD

**Issue by edorossi** [eutelescope/eutelescope#339]
I am using ilcsoft v01-17-05 and I have a problem with a processor. While all the processors run smoothly, there is one processor that doesn't work:

11:01:51 jobsub.alibava-crosstalk-it1(ERROR): ***********************************************
11:01:51 jobsub.alibava-crosstalk-it1(ERROR): A runtime error occured - (uncaught exception):
11:01:51 jobsub.alibava-crosstalk-it1(ERROR): lcio::Exception:  ProcessorMgr::registerProcessor: unknown processor with type AlibavaCrossTalkCalculator !
11:01:51 jobsub.alibava-crosstalk-it1(ERROR): 
11:01:51 jobsub.alibava-crosstalk-it1(ERROR): Marlin will have to be terminated, sorry.
11:01:51 jobsub.alibava-crosstalk-it1(ERROR): ***********************************************

I can't find any significant difference in the source code of this processor with respect to the working ones. When I built EUTelescope, the processor was built without problems, just like the others:
[ 82%] Building CXX object CMakeFiles/Eutelescope.dir/src/alibava/AlibavaCrossTalkCalculator.cc.o

It looks like it is not registered correctly. How can I fix it?

**Comment by tbisanz** [comment]
Is this resolved yet?
