### ISSUE TITLE
EutelMilleGBL.cc 

### ISSUE THREAD

**Issue by j1990grossmann** [eutelescope/eutelescope#368]
Could someone please check wether the following lines are correct. 
As I read it this is the part, where the tetSi, tetAir or tetAlu is the width of the approximate Gaussian calculated with the Highland approximation for multiple coulomb scattering in a thin scatterer.
master/processors/src/EUTelMilleGBL.cc:
1303: ` double tetSi = _kappa*0.0136 * sqrt(epsSi) / p * ( 1 + 0.038*std::log(sumeps) );`
1425 :  `tetAir = _kappa*0.0136 * sqrt(epsAir) / p * ( 1 + 0.038*std::log(sumeps) );`
1444:  `double tetAlu = _kappa*0.0136 * sqrt(epsAlu) / p * ( 1 + 0.038*std::log(sumeps) );`

In my opinion it should hold:
1303: ` double tetSi = _kappa*0.0136 * sqrt(epsSi) / p * ( 1 + 0.038*std::log(epsSi) );`
1425 :  `tetAir = _kappa*0.0136 * sqrt(epsAir) / p * ( 1 + 0.038*std::log(epsAir) );`
1444:  `double tetAlu = _kappa*0.0136 * sqrt(epsAlu) / p * ( 1 + 0.038*std::log(epsAlu) );`

Please correct me if I am wrong.

**Comment by TCThenna** [comment]
Dear Johannes, 

indeed, it took me quite some time to understand it myself, but the code is correct as is.
Please read 
   https://epjti.epj.org/articles/epjti/abs/2016/01/40485_2016_Article_33/40485_2016_Article_33.html
especially section "GBL track fits, multiple scattering and residuals" (alas, the journal does not do section numbering), and try to understand how to go from eq (1) to eq (2).
