### ISSUE TITLE
Example gbl_dut not working

### ISSUE THREAD

**Issue by maweer** [eutelescope/eutelescope#378]
The example gbl_dut is not working at the moment, because only the aligngbl-temp is provided in the steering-templates.
Could you add the other templates which are needed and commend in which order they have to be started?

Thank you.

**Comment by dreyling** [comment]
@tbisanz can you remind me, where exactly the problem is? You said something like hard coded plane IDs, if I remember correctly.

**Comment by edorossi** [comment]
GBL_DUT has been updated and it is part of #447. It will be merged very soon. I close the issue since it is related to an obsolete version of the example.
