### ISSUE TITLE
Inconsistency at install on file path

### ISSUE THREAD

**Issue by clairedavid** [eutelescope/eutelescope#382]
Inconsistency spotted: 

On the website: http://eutelescope.web.cern.ch/content/installation 
It is asked to check the file: $ILCSOFT/ilcinstall_v01-19-02-eutel/releases/v01-17-10/release-versions.py 

This file does not exist, it is instead: $ILCSOFT/ilcinstall/releases/v01-19/release-versions.py

**Comment by tbisanz** [comment]
Modified it to show
```
$ILCSOFT/ilcinstall/releases/vYY-XX/release-versions.py
```
