### ISSUE TITLE
GBL Naming

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#396]
Dear all,

to decouple this a bit from the other threads. Naming. I know this somewhat developed historically, but we have driplets, triplets (I'm Austrian for god's sake, these are the same words!) Furthermorem, triCut, driCut (same again!) and six-cut and many more very unintuitive terms.

If we stick to these terms, we have to explain them somewhere. Maybe it would also be a good time to think about renaming some of them? I don't want to force them being renamed, I'd just like to hear your thoughts and at least get some documentation on them!

**Comment by TCThenna** [comment]
triCut -> tripletResidualCut
driCut -> dripletResidualCut
sixCut -> triplet-driplet-matchingCut

**Comment by tbisanz** [comment]
Is that a suggestion for renaming? If so, I'd go for _tripletDripletMatchingCut_

**Comment by edorossi** [comment]
What about something like upstreamTripletCut, downstreamTripletCut and tripletsMatchingCut? Driplet looks like a typo :)

**Comment by TCThenna** [comment]
upstreamTripletCut does not explain, upon which quantity the cut acts. The cut is on the residual of a straight line (from outer points) extrapolated to the middle plane, and their, the distance b/w the line and the hit.

maybe:
upstreamTripletResidualCut
downstreamTripletResidualCut
tripletsMatchingCut is fine for me

**Comment by tbisanz** [comment]
Let's make a guideline: parameters should be of **theFollowingForm** - for any future processor.

For the naming, I'm perfectly fine with the last suggestions, personally I prefer "upstream" and "downstream" to "tri" and "driplet" as it makes talkign about them much easier. But I don't have any hard feelings towards any suggestions.

**Comment by TCThenna** [comment]
I'm fine with the guideline.

and if Edo is fine with my suggestion, than we can close this issue :D

**Comment by jha92** [comment]
I like the suggestion.
Only to be explicit: we should fix the parameter name to thFollowingForm - for any processor, we "renovate" and would like to maintain in our basic package, so also back-propagating to existing once.

**Comment by edorossi** [comment]
I totally agree with @TCThenna suggestion!

**Comment by TCThenna** [comment]
upstreamTripletSlopeCut (that would pair well to upstreamTripletResidualCut, same style)

**Comment by tbisanz** [comment]
The cut is applied to the up- & downstream triplets: https://github.com/eutelescope/eutelescope/blob/master/processors/src/EUTelAlignGBL.cc#L410-L411, but modified with a hard-coded value. What shall we do there?

**Comment by TCThenna** [comment]
For scattering studies, we need two cuts:
- the triplet (sry, upstreamTriplet) has a small divergence, 
- the downstreamTriplet can have large scattering angles.

So I'd opt for two separate ones. Maybe the `downstreamTripletSlopeCut` is defaulted to the upstream one, and overwritten when specified.

**Comment by tbisanz** [comment]
Decided!
