### ISSUE TITLE
CTest cases produce different output on different machines

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#400]
To move this away from #399 - I added some [test cases](https://github.com/eutelescope/eutelescope/tree/master/ctest/aconite-4chipLocal_test) for the aconite-4ChipLocal example. They check if the same amount of clusters, noisy pixels, tracks, alignment constants etc. are found.

@edorossi found that they slightly differ on his installation. I checked and the differences are very small, it seems that the alignment finds slightly different alignment constants, and thus the aligned sample finds **one more track**. We can easily allow the alignment output to vary in the last digits, and also accept +-10 tracks in the last steps. 

It might still be interesting to find out why this happens.

**Comment by edorossi** [comment]
@tbisanz, can you run the test and put the full output in some public folder? I will try to understand exactly where the difference happens by checking directly the lcio files and the histograms in order to isolate the "problem"

**Comment by tbisanz** [comment]
`/afs/cern.ch/user/t/tbisanz/public/test_07-6_pede_result_log.txt`

**Comment by tbisanz** [comment]
I can upload the rest at some point later

**Comment by tbisanz** [comment]
@dreyling Check out the most recent master branch, build EUTelescope and go to `build` and run `ctest -V -R aco*` - pipe the output into some file!

**Comment by jha92** [comment]
@edorossi  Can we close this for now? Have you found out something back then?

**Comment by edorossi** [comment]
@jha92 we never found how to fix the problem, but I think we have to update the tests anyway, so this issue is not a priority anymore. Let's close it and see if the problem arises again.
