### ISSUE TITLE
Submission handling HTCondor

### ISSUE THREAD

**Issue by schuetzepaul** [eutelescope/eutelescope#407]
Hi all,

this is rather for the colleagues at DESY, although any input is appreciated.
Has anyone tried running jobs or changing the jobsub to be compatible with HTCondor? The SGE system is slowly running out of nodes, hence we should think about it now. Did anyone start on this?

(I ran some HTCondor jobs with other software/scripts, but not EUTelescope yet..)

**Comment by TCThenna** [comment]
we should merge with #406 :D

**Comment by tbisanz** [comment]
Please continue in #406!
