### ISSUE TITLE
gbl_local example

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#417]
Update the GBL local example and verify correct operation!

**Comment by tbisanz** [comment]
This is a updated steering file for the EUTelAlignGBL processor: https://github.com/eutelescope/eutelescope/blob/master/jobsub/examples/gbl_local/steering-templates/aligngbl-tmp.xml#L81-L130

**Comment by tbisanz** [comment]
@edorossi did you ever test the current version of this processor?

**Comment by tbisanz** [comment]
@TCThenna at some point it would be great if you could take a look at this and verify that it's correct, in particular as this shold become the prime example for gbl w/o any DUT!

**Comment by TCThenna** [comment]
I'll put it on my todo list ...

**Comment by jha92** [comment]
Some questions here, as I am currently working on it:
1) why the name gbl_local?
2) is the overload of definitions in config file for not used processors intentionally?

**Comment by tbisanz** [comment]
> why the name gbl_local?
It was the first example which used the gbl processors but the alignment which stores hits in the local frame.
> is the overload of definitions in config file for not used processors intentionally?
Probably not, please link :)

**Comment by jha92** [comment]
Okay, we were here always a bit confused about that.
For the link: [https://github.com/eutelescope/eutelescope/blob/master/jobsub/examples/gbl_local/config.cfg#L69-L502](url)
I mean there e.g. aligndaf, daffitter, etc.

**Comment by dreyling** [comment]
@jha92 and me are working on the gbl_local example to make this example as first starting point for newcomers. Therefore, we need feedback:

- I have moved as many fixed parameters from the template files in the ```config.cfg``` file. Right approach?
- I think it would be nice if every output file will be in the output folder, ok?
  - [ ] ```millepede.*``` files of gbl
  - [ ] jobsub files for ```condor_submit``` (This is need changes in jobsub.py and is not straightforward)
- Why these warnings happens (grepped from the output)? Obsolete parameters, functionalities, etc or is there missing something?
  - [ ] ```gear::TrackerPlanes NOT found```
```
clustering-000117.log:[ WARNING "ClusteringMimosa"] gear::TrackerPlanes NOT found 
converter-000117.log:[ WARNING "HotPixelMasker"] gear::TrackerPlanes NOT found 
hitmaker-000117.log:[ WARNING "HitMakerM26"] gear::TrackerPlanes NOT found 
clustering-000117.log:[ WARNING "ClusteringMimosa"] gear::TrackerPlanes NOT found 
converter-000117.log:[ WARNING "HotPixelMasker"] gear::TrackerPlanes NOT found 
hitmaker-000117.log:[ WARNING "HitMakerM26"] gear::TrackerPlanes NOT found 
aligngbl-000117.log:[ WARNING "HitLocalToGlobal"] gear::TrackerPlanes NOT found 
aligngbl2-000117.log:[ WARNING "HitLocalToGlobal"] gear::TrackerPlanes NOT found 
aligngbl3-000117.log:[ WARNING "HitLocalToGlobal"] gear::TrackerPlanes NOT found 
trackgbltriplet-000117.log:[ WARNING "HitLocalToGlobal"] gear::TrackerPlanes NOT found
```
  - [ ] Why is this missing? Not in raw file? Is this crucial? ```Adding a EORE because was missing```
```
converter-000117.log:[ WARNING "Save"] Adding a EORE because was missing
clustering-000117.log:[ WARNING "Save"] Adding a EORE because was missing
hitmaker-000117.log:[ WARNING "Save"] Adding a EORE because was missing
trackgbltriplet-000117.log:[ WARNING "Save"] Adding a EORE because was missing
```
  - [ ] ```histoinfo.xml``` does not exist. Is this needed? For what exactly?
```
clustering-000117.log:[ WARNING4 "ClusteringMimosa"]  -----------   
clustering-000117.log:[ WARNING4 "ClusteringMimosa"]  the following processor will modify the LCIO event :  ClusteringMimosa !! 
clustering-000117.log:[ WARNING4 "ClusteringMimosa"]  ------------  
clustering-000117.log:[ WARNING2 "ClusteringMimosa"] marlin::ParseException: EUTelHistogramManager::init error in file /nfs/dust/atlas/user/dreyling/eutelescope/v01-19-02/Eutelescope/master/jobsub/examples/gbl_local/steering-templates/histoinfo.xml, row: 0, col: 0 : Failed to open file
clustering-000117.log:[ WARNING2 "ClusteringMimosa"] Continuing without histogram manager
...
hitmaker-000117.log:[ ERROR5 "Correlator"] marlin::ParseException: EUTelHistogramManager::init error in file /nfs/dust/atlas/user/dreyling/eutelescope/v01-19-02/Eutelescope/master/jobsub/examples/gbl_local/steering-templates/histoinfo.xml, row: 0, col: 0 : Failed to open file
hitmaker-000117.log:[ ERROR5 "Correlator"] Continuing without histogram manager using default settings
```
  - [ ] Is this because of the EUDAQ parameter ```GeoID```? Should this be a WARNING or more an INFO?
```
hitmaker-000117.log:[ WARNING3 "HitLocalToGlobal"] EUTelGeometryTelescopeGeoDescription: Geometry already initialized, using old initialization
hitmaker-000117.log:[ WARNING3 "Correlator"] EUTelGeometryTelescopeGeoDescription: Geometry already initialized, using old initialization
hitmaker-000117.log:[ WARNING0 "HitMakerM26"] The geometry ID in the run header is set to zero.
hitmaker-000117.log:[ WARNING0 "HitMakerM26"] This may mean that the GeoID parameter was not set
hitmaker-000117.log:[ WARNING0 "Correlator"] The geometry ID in the run header is set to zero.
hitmaker-000117.log:[ WARNING0 "Correlator"] This may mean that the GeoID parameter was not set
...
aligngbl-000117.log:[ WARNING3 "PedeToGEAR"] EUTelGeometryTelescopeGeoDescription: Geometry already initialized, using old initialization
aligngbl-000117.log:[ WARNING3 "MyEUTelAlignGBL"] EUTelGeometryTelescopeGeoDescription: Geometry already initialized, using old initialization
```

**Comment by TCThenna** [comment]
>I think it would be nice if every output file will be in the output folder, ok?
>
>    millepede.* files of gbl
>   jobsub files for condor_submit (This would need changes in jobsub.py and is not straightforward --> not first priority)

There are also folders with the run nunber created, that contain the log files. Or did you mean these when saying "jobsub files"?

> Why these warnings happens (grepped from the output)? Obsolete parameters, functionalities, etc or is there missing something?

>    gear::TrackerPlanes NOT found

I have no clue.

> Why is this missing? Not in raw file? Is this crucial?

Maybe you defined a maxEvent which is smaller then the actual recorded number of events, so the EORE was cut of?

> histoinfo.xml

I think it was used to make some histo settings configurable rather than hardcoded. Maybe this is a functionality we should keep in principle?

**Comment by TCThenna** [comment]
this is what is in my histoinfo.xml

<HistogramManager>
  <histos>

     
    <histo name="RawDataDistHisto"  type="H1D" xBin="4096" xMin="-2048.5" xMax="2047.5"/>
    <histo name="DataDistHisto"     type="H1D" xBin="5000" xMin="-500"    xMax="500" />
    <histo name="CommonDistHisto"   type="H1D" xBin="100"  xMin="-10"     xMax="10" />

    
    <histo name="HitCloudLocal"     type="C2D" />
    <histo name="HitCloudTelescope" type="C2D" />
    <histo name="DensityPlot"       type="C3D" />

    
    <histo name="PedeDist"          type="H1D" xBin="100"  xMin="-20"     xMax="29"/>
    <histo name="NoiseDist"         type="H1D" xBin="100"  xMin="-5"      xMax="15"/>
    <histo name="CommonMode"        type="H1D" xBin="100"  xMin="-2"      xMax="2" />

    
    <histo name="clusterSignal"     type="H1D" xBin="1000" xMin="0"        xMax="1000"/>
    <histo name="clusterNoise"      type="H1D" xBin="70"  xMin="0"        xMax="50"/>
    <histo name="seedSignal"        type="H1D" xBin="500" xMin="0"        xMax="300"/>
    <histo name="seedSNR"           type="H1D" xBin="150" xMin="0"        xMax="100"/>
    <histo name="clusterSNR"        type="H1D" xBin="200" xMin="0"        xMax="150"/>
    <histo name="eventMultiplicity" type="H1D" xBin="60"  xMin="0"        xMax="60"/>

    
    



    
    <histo name="logChi2"     type="H1D" xBin="200" xMin="-1"      xMax="9"/>
    <histo name="nTrack"      type="H1D" xBin="10"  xMin="-0.5"    xMax="9.5"/>
    <histo name="nHit"        type="H1D" xBin="10"  xMin="-0.01"   xMax="9.99"/>


    
    <histo name="measuredX"    type="H1D" xBin="200" xMin="-10" xMax="10"/>
    <histo name="measuredY"    type="H1D" xBin="100" xMin="-5" xMax="5"/>
    <histo name="measuredXY"   type="H2D" xBin="200" xMin="-10" xMax="10" 
                                          yBin="100" yMin="-5" yMax="5"/>


    <histo name="fittedX"    type="H1D" xBin="200" xMin="-10" xMax="10"/>
    <histo name="fittedY"    type="H1D" xBin="100" xMin="-5" xMax="5"/>
    <histo name="fittedXY"   type="H2D" xBin="200" xMin="-10" xMax="10" 
                                        yBin="100" yMin="-5" yMax="5"/>


    <histo name="residualX"    type="H1D" xBin="500" xMin="-0.50" xMax="0.50"/>
    <histo name="residualY"    type="H1D" xBin="500" xMin="-0.50" xMax="0.50"/>
    <histo name="residualXY"   type="H2D" xBin="500" xMin="-0.50" xMax="0.50" 
                                          yBin="500" yMin="-0.50" yMax="0.50"/>

    <histo name="beamShiftX"    type="H1D" xBin="100" xMin="-2" xMax="2"/>
    <histo name="beamShiftY"    type="H1D" xBin="100" xMin="-2" xMax="2"/>

    <histo name="beamRotX"    type="H1D" xBin="200" xMin="-10" xMax="10"/>
    <histo name="beamRotY"    type="H1D" xBin="100" xMin="-5" xMax="5"/>
    <histo name="beamRotX2D"  type="H2D" xBin="200" xMin="-10" xMax="10" yBin="100" yMin="-1.5" yMax="1.5" />
    <histo name="beamRotY2D"  type="H2D" xBin="100" xMin="-5" xMax="5" yBin="100" yMin="-1.5" yMax="1.5" />
    <histo name="beamRotX"    type="P1D" xBin="200" xMin="-10" xMax="10" yMin="-1.5" yMax="1.5" />
    <histo name="beamRotY"    type="P1D" xBin="100" xMin="-5" xMax="5" yMin="-1.5" yMax="1.5" />

    
            <histo name="DUTshiftY"     type="H1D" xBin="300" xMin="-0.15" xMax="0.15"/>
            <histo name="DUTshiftX"     type="H1D" xBin="300" xMin="-0.15" xMax="0.15"/>

    
    <histo name="orchi2GblFit"    type="H1D" xBin="500" xMin="0." xMax="1000."/>
    <histo name="orchi2ndfGblFit" type="H1D" xBin="500" xMin="0." xMax="100."/>
    <histo name="orprobGblFit"    type="H1D" xBin="500" xMin="0." xMax="1."/>
    <histo name="chi2GblFit"      type="H1D" xBin="500" xMin="0." xMax="1000."/>
    <histo name="chi2ndfGblFit"   type="H1D" xBin="500" xMin="0." xMax="100."/>
    <histo name="probGblFit"      type="H1D" xBin="500" xMin="0." xMax="1."/>
    <histo name="Residuals2DGblFit_yVSx0"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy0"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSx1"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy1"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSx2"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy2"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSx3"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy3"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSx4"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy4"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSx5"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_yVSy5"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx0"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy0"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx1"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy1"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx2"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy2"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx3"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy3"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx4"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy4"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSx5"     type="H2D"  xBin="100" xMin="-10." xMax="10." yBin="100" yMin="-10." yMax="10."/>
    <histo name="Residuals2DGblFit_xVSy5"     type="H2D"  xBin="100" xMin="-05." xMax="05." yBin="100" yMin="-10." yMax="10."/>
    <histo name="ResidualsGblFit_x0"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y1"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_x1"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y2"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_x2"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y3"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_x3"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y3"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_x4"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y4"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_x5"     type="H1D" xBin="500" xMin="-20." xMax="20."/>
    <histo name="ResidualsGblFit_y5"     type="H1D" xBin="500" xMin="-20." xMax="20."/>


  </histos>
</HistogramManager>

**Comment by edorossi** [comment]
The example has been updated and it is now called GBL_noDUT. It is part of #447. I close the issue since it is related to an obsolete version of the example.
