### ISSUE TITLE
Naf installation failed due to removing make_uniqe c++11 style --> use EUDAQ tag v1.8.1

### ISSUE THREAD

**Issue by dreyling** [eutelescope/eutelescope#436]
We have to update the installer to use EUDAQ tag v1.8._**1**_ (which uses/requires c++14 compiler).

@tbisanz @jh92

**Comment by tbisanz** [comment]
Will take care of that tomorrow! Thanks :)

**Comment by jha92** [comment]
I just successfully re-installed EUTel with these changes.
The only thing I had to do was changing in 
`$ILCSOFT/ilcinstall/releases/v01-19/release-versions.py` 
from
`Eudaq_version = "tags/v1.8.0"`  
to 
`Eudaq_version = "tags/v1.8.1"`.
Guess you will change this in the ilcInstaller, @tbisanz ?
Good work @dreyling :)

**Comment by dreyling** [comment]
Done: https://github.com/eutelescope/iLCInstall/commit/43d1d4fc773eacef874fdf1158a39ee121afcf01
