### ISSUE TITLE
ENH: Update EUTELESCOPE.h to include new RD53A det. description at EUDAQ

### ISSUE THREAD

**Issue by duartej** [eutelescope/eutelescope#438]
Hi @tbisanz , could you please update the `EUTelDetectorType` with a new type `kRD53A = 109;` in the  EUTELESCOPE.h  in order to be able to use the new RD53A geometry? This is included in EUDAQ since merge [#469](https://github.com/eudaq/eudaq/pull/469) 
Thanks!!

**Comment by tbisanz** [comment]
Anything else? I'll merge once the CI passes (but it shouldn't fail)

**Comment by duartej** [comment]
Thanks @tbisanz. I don't think any other change related with that is needed, but I will come back to you if so
