### ISSUE TITLE
Remove obsolete processors, code and files

### ISSUE THREAD

**Issue by hperrey** [eutelescope/eutelescope#5]
There are a number of obsolete/redundant/non-functional processors that should be removed. Others are currently in use but will be obsolete soon -- we should test the new processors against the results of the old ones and remove the latter ones afterwards.

- Should already be obsolete (but might still have dependencies that need to be removed)
- [ ] EUTelReferenceHit
- [ ] EUTelProcessorTrackingExhaustiveTrackSearch

- soon obsolete/need to test against, then remove (tbd):
- [ ] EUTelMille (see issue #19)
- [ ] EUTelApplyAlignmentProcessor
- [x] all APIX-specific processors

- Check if really (still) needed:
- [X] EUTelUtilityRungeKutta.cc

**Comment by tbisanz** [comment]
Issue moved to #210 with the remaining files with updated schedule
