### ISSUE TITLE
Installation of EUTelescope with ILCSoft installer using git

### ISSUE THREAD

**Issue by hperrey** [eutelescope/eutelescope#7]
- [x] download EUTel via git from GitHub in ilcinstall
- [x] merge changes into main ilcinstall trunk (ask ILCSoft maintainer for permission)
- [x] tag ilcsoft-install
- [x] update documentation on installation instructions
- [x] add documentation for developers on how to commit changes back

**Comment by tbisanz** [comment]
We have all these features already, the git installation ilcsoft-install tag, comments on the website and the https://github.com/eutelescope/eutelescope/blob/master/CONTRIBUTING.md
