### ISSUE TITLE
Make use of new geometry framework in all processors

### ISSUE THREAD

**Issue by hperrey** [eutelescope/eutelescope#8]
- [x] create local -> global and global -> local transformation processor
- [ ] remove coordinate transformation routines from existing processors
- [ ] clearly mark expected input to processors (if not local coordinates)
- [x] replace "guessSensorID" routines (now separate issue #25)
- [x] remove special handling of e.g. clusters containing hotpixel -- could be managed by either filtering (see #12) or tagging (see #11) (now separate issue #26)

**Comment by tbisanz** [comment]
Grep ```grep -r 'getSiPlanesParameters()' .``` and for ```grep -r '#include <gear/SiPlanesParameters.h>' .``` in the src and include directory. Replace these calls by EUTelGeometryTelescopeGeo functions to complete this issue.
