### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by andrewjblue** [eutelescope/eutelescope#89]
Hi There
I've tried to run though a few examples

Thare are no gear files with the anemone 2 fei4 example code
There's no access to the quad fei4 data files example

Cheers

Andy

**Comment by lime86** [comment]
Hi,

I'm using Eutelescope v1.0 running on lxplus and have the same issue with the alignment:

14:48:46 jobsub.align(ERROR): [ ERROR5 "Align"] STOP ... no variable global parameters
14:48:46 jobsub.align(ERROR): [ ERROR5 "Align"] Problem during Pede execution, exit status: 0, error messages (repeated here):
14:48:46 jobsub.align(ERROR): [ ERROR5 "Align"] STOP ... no variable global parameters
14:48:46 jobsub.align(ERROR): [ ERROR5 "Align"]
14:48:46 jobsub.align(ERROR): [ ERROR5 "Align"] Will exit now

I also took the steering files from the examples, aconite-4chip, running converter -> clustering -> hitmaker -> align -> fitter, no geo-reconstruction. I was using ILCSOFT1.17.05 and had the same issue.

Cheers

Lingxin
