### ISSUE TITLE
LCIO build fails if old ROOT already installed

### ISSUE THREAD

**Issue by pheloniusfriar** [eutelescope/eutelescope#92]
I was building the distribution from scratch (Ubuntu 10.04, 32-bit). ROOT compiled fine (5.34.05); however, when LCIO went to build, it found my old version of ROOT (5.18.00) installed at the system level rather than the new version built for EUTelescope and refused to compile any further... I traced the problem to the file: lcio/v02-04-02/cmake/FindROOT.cmake and the line "FIND_PROGRAM( ROOT_CONFIG_EXECUTABLE root-config PATHS ${ROOT_DIR}/bin NO_DEFAULT_PATH )" where "ROOT_DIR" does not appear to be set correctly, so cmake goes on to find the installed 5.18.00 version of root-config. The build output is below, I will attach the log file.
###### 
###### 

[...]

-- Check for ROOT_CONFIG_EXECUTABLE: /usr/bin/root-config
-- Check for ROOT (5.18.00)
-- Check for ROOT_EXECUTABLE: /usr/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /usr/bin/rootcint

[...]

CMake Error at /usr/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find ROOT (missing: PACKAGE_VERSION_COMPATIBLE) (Required is at
  least version "5.27.06")
Call Stack (most recent call first):
  /usr/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindROOT.cmake:299 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:57 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!

**Comment by tbisanz** [comment]
This should be covered by #311
